#!/bin/sh

PROG=main

rm -f "../$PROG" 8.out *.8

8g -I "$HOME/work/diamond-lang/go/pkg/linux_386/" "$PROG.go" || exit 1
8l -L "$HOME/work/diamond-lang/go/pkg/linux_386/" -o "../$PROG" "$PROG.8"

rm -f "$PROG.8"
